# Generated by Django 2.2 on 2021-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertheme',
            name='color',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='supertheme',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
