# Generated by Django 2.2 on 2021-01-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_auto_20210104_2325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='idea_ieraksts',
        ),
        migrations.AlterModelTable(
            name='supertheme',
            table='idea_super_tema',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='idea_tema',
        ),
    ]
