# Generated by Django 2.2 on 2021-01-14 13:28

from django.db import migrations, models
import django.db.models.deletion
import idea.models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_auto_20210111_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Idea_ieraksti'},
        ),
        migrations.AlterModelOptions(
            name='supertheme',
            options={'verbose_name_plural': 'Idea_temas'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name_plural': 'Idea_temas'},
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=idea.models.upload_path)),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Post')),
            ],
            options={
                'verbose_name_plural': 'Idea_attēli',
                'db_table': 'idea_images',
            },
        ),
    ]
