# Generated by Django 2.2 on 2021-01-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_auto_20210114_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Ideju Lāde - ieraksti'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name_plural': 'Ideju Lāde - attēli'},
        ),
        migrations.AlterModelOptions(
            name='supertheme',
            options={'verbose_name_plural': 'Ideju Lāde - tabi'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name_plural': 'Ideju Lāde - tēmas'},
        ),
    ]
