# Generated by Django 2.2 on 2021-01-14 14:02

from django.db import migrations, models
import idea.models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_auto_20210114_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=idea.models.upload_new_path),
        ),
    ]
