# Generated by Django 2.2 on 2021-01-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_auto_20210114_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
