# Generated by Django 2.2 on 2020-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobobj',
            name='obj_zone',
            field=models.CharField(choices=[('maja', 'māja'), ('IT', 'IT'), ('lapene', 'lapene'), ('skjunis', 'šķūnis'), ('elektriba', 'elektrība'), ('santehnika', 'santehnika'), ('instrument', 'instrumenti'), ('darzs', 'dārzs'), ('zogs', 'žogs'), ('grods', 'grods'), ('koki', 'koki'), ('cits', 'cits'), ('KUVALDA', 'TrailCamPhoto'), ('GRAVANI', 'IT-Projekti')], default='cits', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobs_zone',
            field=models.CharField(choices=[('maja', 'māja'), ('IT', 'IT'), ('lapene', 'lapene'), ('skjunis', 'šķūnis'), ('elektriba', 'elektrība'), ('santehnika', 'santehnika'), ('instrument', 'instrumenti'), ('darzs', 'dārzs'), ('zogs', 'žogs'), ('grods', 'grods'), ('koki', 'koki'), ('cits', 'cits'), ('KUVALDA', 'TrailCamPhoto'), ('GRAVANI', 'IT-Projekti')], default='IT', max_length=10, verbose_name='Darba zona'),
        ),
    ]
