# Generated by Django 2.2 on 2020-12-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200306_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobs_type',
            field=models.CharField(choices=[('ATRAST', 'atrast'), ('JADARA', 'jādara'), ('PETIT', 'izpētīt apdomāt'), ('JAPERK', 'jāpērk'), ('VEST', 'transports'), ('SVARIGI', 'svarīgi')], default='JADARA', max_length=10, verbose_name='Darba veids/svarīgums'),
        ),
    ]
