# Generated by Django 2.2 on 2020-12-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201217_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobs_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
