# Generated by Django 2.2 on 2021-01-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20201227_2115'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobobj',
            table='jobs_objects',
        ),
        migrations.AlterModelTable(
            name='jobobj_file',
            table='jobs_objects_files',
        ),
        migrations.AlterModelTable(
            name='jobobj_image',
            table='jobs_objects_images',
        ),
    ]
