# Generated by Django 2.2 on 2021-01-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210111_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsZones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=20)),
                ('special', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'jobs_zones',
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobsZones'),
        ),
    ]
