# Generated by Django 2.2 on 2021-01-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobs_jobs_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='zone',
            new_name='jobs_zone',
        ),
    ]
