# Generated by Django 2.2 on 2021-01-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210129_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Darbu saraksts'},
        ),
        migrations.AlterModelOptions(
            name='jobszones',
            options={'verbose_name_plural': 'Darbu zonas'},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobs_zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobsZones'),
        ),
    ]
