# Generated by Django 2.2 on 2021-01-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_jobobj_obj_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobobj',
            old_name='zone',
            new_name='obj_zone',
        ),
    ]
