# Generated by Django 2.2 on 2021-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210129_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(default='', max_length=20)),
                ('color', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Darbu veidi',
                'db_table': 'jobs_types',
            },
        ),
    ]
