# Generated by Django 2.2 on 2021-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobstypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstypes',
            name='color',
            field=models.CharField(default='#f5f5f5', max_length=10),
        ),
    ]
