# Generated by Django 2.2 on 2021-01-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20210129_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobsTypes'),
        ),
    ]
