# Generated by Django 2.2 on 2021-01-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobs_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='jobs_type',
        ),
    ]
