# Generated by Django 2.2 on 2021-01-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_remove_jobs_jobs_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='type',
            new_name='jobs_type',
        ),
    ]
