# Generated by Django 2.2 on 2021-01-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20210129_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstypes',
            name='marking_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
