# Generated by Django 2.2 on 2021-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobstypes_marking_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstypes',
            name='started_color',
            field=models.CharField(default='#f5f5f5', max_length=10),
        ),
    ]
