# Generated by Django 2.2 on 2021-01-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_jobstypes_started_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobobj',
            options={'verbose_name_plural': 'Lietu parametri'},
        ),
        migrations.AlterModelOptions(
            name='jobobj_file',
            options={'verbose_name_plural': 'Lietu parametru faili'},
        ),
        migrations.AlterModelOptions(
            name='jobobj_image',
            options={'verbose_name_plural': 'Lietu parametru attēli'},
        ),
    ]
