# Generated by Django 3.0.3 on 2020-03-01 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galery_date', models.DateField(default=django.utils.timezone.now)),
                ('galery_img', models.ImageField(upload_to='galery/')),
                ('galery_thumb', models.ImageField(blank=True, null=True, upload_to='galery/thumb/')),
                ('galery_public', models.BooleanField(default=False)),
                ('galery_tags', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'galerija',
            },
        ),
    ]
