# Generated by Django 2.2 on 2021-01-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='galery',
            table='gallery',
        ),
    ]
