# Generated by Django 3.0.3 on 2020-03-01 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('poweroff', 'shut down desktop'), ('rescale', 'rescale'), ('imgtovid', 'image to video'), ('chkvid', 'check video integrity')], default='imgtovid', max_length=30)),
                ('task_object', models.CharField(max_length=50)),
                ('task_time', models.DateTimeField(blank=True, null=True)),
                ('task_input', models.CharField(max_length=50)),
                ('task_output', models.CharField(max_length=50)),
                ('task_status', models.BooleanField(default=False)),
                ('task_wait', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'server_tasks',
            },
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_last_visit', models.DateTimeField(blank=True, null=True)),
                ('video_live', models.BooleanField(default=False)),
                ('video_live_local', models.BooleanField(default=False)),
                ('video_archive', models.BooleanField(default=False)),
                ('galery', models.BooleanField(default=False)),
                ('galery_add', models.BooleanField(default=False)),
                ('sm_electr', models.BooleanField(default=False)),
                ('sm_termo', models.BooleanField(default=False)),
                ('sm_led', models.BooleanField(default=False)),
                ('job_list', models.BooleanField(default=False)),
                ('job_add', models.BooleanField(default=False)),
                ('job_start', models.BooleanField(default=False)),
                ('job_cancel', models.BooleanField(default=False)),
                ('job_fin', models.BooleanField(default=False)),
                ('job_restart', models.BooleanField(default=False)),
                ('job_mark', models.BooleanField(default=False)),
                ('obj_list', models.BooleanField(default=False)),
                ('obj_list_add', models.BooleanField(default=False)),
                ('obj_list_edit', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('garden_add', models.BooleanField(default=False)),
                ('map', models.BooleanField(default=False)),
                ('user_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.CreateModel(
            name='Live_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('cookie_uuid', models.CharField(default='', max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_video_log',
            },
        ),
    ]
