# Generated by Django 2.2 on 2020-12-16 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200403_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('radio', models.CharField(choices=[('poweroff', 'shut down desktop'), ('rescale', 'rescale'), ('imgtovid', 'image to video'), ('chkvid', 'check video integrity')], default='imgtovid', max_length=30)),
                ('chk_1', models.BooleanField(default=False)),
                ('chk_2', models.BooleanField(default=False)),
                ('chk_3', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'map_plot_points',
            },
        ),
    ]
