# Generated by Django 2.2 on 2020-12-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201217_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplot',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='mapplot',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
