# Generated by Django 2.2 on 2020-12-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201217_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplot',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mapplot',
            name='lon',
            field=models.CharField(max_length=50),
        ),
    ]
