# Generated by Django 2.2 on 2020-12-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201217_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplot',
            name='radio',
            field=models.CharField(choices=[('red', 'sarkans'), ('green', 'zaļš'), ('blue', 'zils')], default='red', max_length=10),
        ),
    ]
