# Generated by Django 2.2 on 2020-12-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20201217_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapPlot',
        ),
    ]
