# Generated by Django 2.2 on 2020-12-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0017_elconsumption_coment'),
        ('login', '0012_delete_mapplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smhouse.Location'),
        ),
    ]
