# Generated by Django 2.2 on 2021-01-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_user_data_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='garden',
            new_name='idea',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='garden_add',
            new_name='idea_add',
        ),
    ]
