# Generated by Django 2.2 on 2021-01-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20210111_1923'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='live_video',
            table='login_live_video_log',
        ),
        migrations.AlterModelTable(
            name='server_task',
            table='login_server_tasks',
        ),
        migrations.AlterModelTable(
            name='user_data',
            table='login_user_data',
        ),
    ]
