# Generated by Django 2.2 on 2021-05-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210111_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server_task',
            old_name='task_status',
            new_name='task_done',
        ),
    ]
