# Generated by Django 2.2 on 2021-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_server_task_task_done_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_task',
            name='task_object',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
