# Generated by Django 2.2 on 2021-06-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20210514_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_video',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
