# Generated by Django 2.2 on 2020-12-18 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('radio', models.CharField(choices=[('red', 'sarkans'), ('green', 'zaļš'), ('blue', 'zils')], default='red', max_length=10)),
                ('chk_1', models.BooleanField(default=False)),
                ('chk_2', models.BooleanField(default=False)),
                ('chk_3', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'map_plot_points',
            },
        ),
    ]
