# Generated by Django 2.2 on 2020-12-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapplot', '0002_auto_20201218_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplot',
            name='mark',
            field=models.CharField(default='', max_length=8),
        ),
    ]
