# Generated by Django 2.2 on 2020-12-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapplot', '0004_mapplotcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplot',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapplot.MapPlotCity'),
        ),
    ]
