# Generated by Django 2.2 on 2020-12-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapplot', '0006_remove_mapplot_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapplot',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapplot.MapPlotCity'),
        ),
    ]
