# Generated by Django 2.2 on 2020-12-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapplot', '0008_auto_20201221_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplot',
            name='radio',
            field=models.CharField(choices=[('yellow', 'stabs'), ('green', 'kaste')], default='red', max_length=10),
        ),
    ]
