# Generated by Django 2.2 on 2020-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.SlugField(default='<function uuid4 at 0x7f64947128c8>', unique=True),
        ),
    ]
