# Generated by Django 2.2 on 2020-05-03 15:11

import button.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_auto_20200503_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.SlugField(default=button.models.meeting_id, unique=True),
        ),
    ]
