# Generated by Django 2.2 on 2020-05-03 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0003_auto_20200503_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
