# Generated by Django 2.2 on 2020-05-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0005_auto_20200503_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.SlugField(default='25ffb9b6feaa', unique=True),
        ),
    ]
