# Generated by Django 2.2 on 2020-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0006_auto_20200504_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.SlugField(default='70bcec0ad376', unique=True),
        ),
    ]
