# Generated by Django 2.2 on 2020-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0007_auto_20200504_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.SlugField(default='9f0b959ccf71', unique=True),
        ),
        migrations.AlterField(
            model_name='meetingbutton',
            name='time_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
