# Generated by Django 2.2 on 2020-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0008_auto_20200505_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.SlugField(default='367281e8ecc5', unique=True),
        ),
        migrations.AlterField(
            model_name='meetingbutton',
            name='time_remaining',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
