# Generated by Django 3.0.3 on 2020-03-01 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_name', models.CharField(max_length=100)),
                ('cam_visible', models.BooleanField(default=True)),
                ('cam_slug', models.SlugField(unique=True)),
                ('cam_nr', models.IntegerField(default=1)),
                ('cam_img', models.BooleanField(default=False)),
                ('cam_stream', models.BooleanField(default=False)),
                ('cam_user', models.CharField(default='username', max_length=50)),
                ('cam_url', models.URLField(blank=True, default='http://', null=True)),
                ('cam_url_local', models.URLField(blank=True, default='http://', null=True)),
                ('cam_url_stream', models.URLField(blank=True, default='http://', null=True)),
                ('cam_width', models.IntegerField(default=640)),
                ('cam_height', models.IntegerField(default=320)),
            ],
            options={
                'db_table': 'kameras',
            },
        ),
        migrations.CreateModel(
            name='Camera_online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cam_01', models.BooleanField(default=False)),
                ('cam_02', models.BooleanField(default=False)),
                ('cam_03', models.BooleanField(default=False)),
                ('cam_04', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'kameras_online',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50)),
                ('video_date', models.DateField(default=django.utils.timezone.now)),
                ('video_file', models.FileField(default='', max_length=200, upload_to=video.models.get_file_path)),
                ('video_cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Camera')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
