# Generated by Django 2.2 on 2021-01-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_videodaycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name_plural': 'Kameras'},
        ),
        migrations.AlterModelOptions(
            name='camera_online',
            options={'verbose_name_plural': 'Kameras onlainā'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Videoklipi'},
        ),
        migrations.AlterModelOptions(
            name='videodaycomment',
            options={'verbose_name_plural': 'Video arhīva dienu komentāri'},
        ),
    ]
