# Generated by Django 2.2 on 2021-01-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20210111_1929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camera',
            table='video_cameras',
        ),
        migrations.AlterModelTable(
            name='camera_online',
            table='video_cameras_online',
        ),
    ]
