# Generated by Django 2.2 on 2021-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20210510_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_prefix',
            field=models.CharField(default='', max_length=3),
        ),
    ]
