# Generated by Django 2.2 on 2021-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_camera_cam_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodaycomment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
