# Generated by Django 3.0.3 on 2020-03-01 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('read', models.IntegerField()),
                ('cons', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('cons_days', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'sm_elekto_paterins',
            },
        ),
        migrations.CreateModel(
            name='LedTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('days', models.CharField(default='1111111', max_length=7)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('bright', models.IntegerField(blank=True, null=True)),
                ('effect', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_led',
            },
        ),
    ]
