# Generated by Django 2.2 on 2020-03-19 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'sm_termo_adress',
            },
        ),
        migrations.CreateModel(
            name='TermoPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=30, null=True)),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smhouse.TermoAdress')),
            ],
            options={
                'db_table': 'sm_termo_place',
            },
        ),
        migrations.CreateModel(
            name='TermoReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reading', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smhouse.TermoPlace')),
            ],
            options={
                'db_table': 'sm_termo_reading',
            },
        ),
    ]
