# Generated by Django 2.2 on 2020-03-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0002_termoadress_termoplace_termoreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoadress',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termoplace',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
