# Generated by Django 2.2 on 2020-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0003_auto_20200319_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoadress',
            name='slug',
            field=models.SlugField(default='ktc'),
        ),
    ]
