# Generated by Django 2.2 on 2020-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0004_termoadress_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termoreading',
            old_name='reading',
            new_name='humy',
        ),
        migrations.AddField(
            model_name='termoreading',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
