# Generated by Django 2.2 on 2020-03-20 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0005_auto_20200320_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termoreading',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
