# Generated by Django 2.2 on 2020-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0006_auto_20200320_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termoreading',
            name='humy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='termoreading',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
