# Generated by Django 2.2 on 2020-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0007_auto_20200321_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoplace',
            name='ambient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termoplace',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='termoplace',
            name='regex',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
