# Generated by Django 2.2 on 2020-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0008_auto_20200322_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoplace',
            name='filename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
