# Generated by Django 2.2 on 2020-03-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0009_termoplace_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termoplace',
            name='regex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
