# Generated by Django 2.2 on 2020-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0011_auto_20200322_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termoplace',
            name='regex',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
