# Generated by Django 2.2 on 2020-03-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0012_auto_20200322_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermoAdress',
            new_name='Location',
        ),
    ]
