# Generated by Django 2.2 on 2020-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0013_auto_20200330_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termoplace',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
