# Generated by Django 2.2 on 2020-04-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0014_auto_20200331_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bw_color_log',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='sun_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
