# Generated by Django 2.2 on 2020-04-06 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0015_auto_20200406_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sunrise', models.DateTimeField(default=django.utils.timezone.now)),
                ('sunset', models.DateTimeField(default=django.utils.timezone.now)),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smhouse.Location')),
            ],
            options={
                'db_table': 'sm_sun',
            },
        ),
    ]
