# Generated by Django 2.2 on 2020-12-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smhouse', '0016_sundata'),
    ]

    operations = [
        migrations.AddField(
            model_name='elconsumption',
            name='coment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
